### ISSUE TITLE
share the source code

### ISSUE THREAD

**Issue by Qiaoyuanpity** [mlresearch/v143#1]
hello，Can you share the source code？

**Comment by lawrennd** [comment]
Hi Qiao Yuan, 

This is the PMLR publication website, are you asking for the source code to be shared for that? Or a particular paper.

Neil

**Comment by Qiaoyuanpity** [comment]
I just want to learn the author's code,because there's still a lot of confusion just looking at the paper.I sincerely hope you can share it.Thanks.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mlresearch/v143"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月21日(星期四) 上午7:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mlresearch/v143] share the source code (Issue #1)





 
Hi Qiao Yuan,
 
This is the PMLR publication website, are you asking for the source code to be shared for that? Or a particular paper.
 
Neil

**Comment by lawrennd** [comment]
You need to contact the author for that. PMLR is th publisher.



Neil
―
Professor Neil Lawrence
http://inverseprobability.com
________________________________

**Comment by Qiaoyuanpity** [comment]
ok,thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mlresearch/v143"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月21日(星期四) 晚上6:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mlresearch/v143] share the source code (Issue #1)





 You need to contact the author for that. PMLR is th publisher. 
 
 
 
 Neil 
 ― 
 Professor Neil Lawrence 
 http://inverseprobability.com 
 ________________________________
